language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
    - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate();
          using Coverage; Coveralls.submit(Coveralls.process_folder())'
